esphome:
  name: sensor-de-porta-tuya-1
  friendly_name: Sensor de porta Tuya 1
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  includes:
    - sb1_uart.h

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.68.129
    subnet: 255.255.255.0
    gateway: 192.168.68.1

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
  shutdown_message:
  will_message:

uart:
  - tx_pin: 1
    rx_pin: 3
    baud_rate: 9600
    id: uart_0

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG
  hardware_uart: UART1

sensor:
  - platform: wifi_signal
    name: "Door WiFi Signal"
    update_interval: never
    expire_after:
    filters: []
  - platform: adc
    name: "Door Battery"
    update_interval: never
    expire_after:
    pin: VCC
    filters: []

binary_sensor:
  - platform: template
    state_topic: "home-assistant/sensor-de-porta-tuya-1/state"
    id: door
    name: "Door Closure"
    filters: []
    device_class: door
    lambda: "return {};"

custom_component:
  - id: sb1_uart
    lambda: |-
      auto component = new SB1UARTComponent(id(uart_0), id(door));
      return {component};
